### ISSUE TITLE
Use clang-format and clang-tidy on all sources

### ISSUE THREAD

**Issue by ckaran** [JuliaLang/libosxunwind#8]
Consider running [clang-format](http://clang.llvm.org/docs/ClangFormat.html) and [clang-tidy](http://clang.llvm.org/extra/clang-tidy/) on all of the C and C++ code.  You will need to eyeball it afterwards to make sure it is visually correct, but it tends to make code a lot clearer.

**Comment by Keno** [comment]
This code base is not being actively developed. As such I would avoid making changes unless to correct a bug.

**Comment by tkelman** [comment]
Isn't this code present in upstream LLVM nowadays?

**Comment by ckaran** [comment]
@Keno Got it.  @tkelman Which equivalent code is being actively developed in LLVM? Is that what Julia is now using exclusively (that is, if I get changes to the LLVM line, will Julia reflect it eventually?)

**Comment by Keno** [comment]
We are currently still using this library. I would happily accept a pull request to replace the code in this repository by upstream llvm (https://github.com/llvm-mirror/libunwind) with our assembly profiling patches applied. One could also try submitting those patches upstream, but it is somewhat unlikely that they would be merged, since unwinding at non-callsites is not a design goal of the library and though these patches work fairly well in practice, they're still a bit of a hack.

**Comment by ckaran** [comment]
@Keno I don't understand either LLVM's or Julia's code bases well enough to safely merge them, especially if there are significant differences between the two bases at this point.  Have you tried submitting the changes upstream yourself?

**Comment by vtjnash** [comment]
We probably want to minimize the diff here, to be able to compare changes, so we won't do this.
